apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop

spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      name: online-shop-pod
      labels:
        app: online-shop
    spec:
      containers:
        - name: online-shop-container
          image: deploykarle/online_shop:v1.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "250Mi"
